// DesignLift — Output formatters
// Runs in popup context. Transforms raw scan data into export formats.

DLFormat = {

  // Helper: get first color of a category
  _getColor(data: any, category: string, idx = 0): string {
    return (data.colors || []).filter((c: any) => c.category === category)[idx]?.hex || '';
  },

  // ─── DESIGN SYSTEM TS ──────────────────────────────────────────────

  toDesignSystem(data: any): string {
    const url = data.sourceUrl || 'unknown';
    const date = data.timestamp?.split('T')[0] || new Date().toISOString().split('T')[0];

    const bg = this._getColor(data, 'background') || '#ffffff';
    const surface = this._getColor(data, 'surface') || '#f5f5f5';
    const border = this._getColor(data, 'border') || '#e5e5e5';
    const textP = this._getColor(data, 'text-primary') || '#171717';
    const textS = this._getColor(data, 'text-secondary') || '#525252';
    const textM = this._getColor(data, 'text-muted') || '#a3a3a3';
    const accent = this._getColor(data, 'accent') || '#3b82f6';

    const typo = data.typography || [];
    const headingFont = typo.find((t: any) => ['hero', 'h1'].includes(t.role))?.fontFamily || data.fontStack?.families?.[0] || 'sans-serif';
    const bodyFont = typo.find((t: any) => t.role === 'body')?.fontFamily || data.fontStack?.families?.[0] || 'sans-serif';

    const fontSizes: Record<string, string> = {};
    typo.forEach((t: any) => { fontSizes[t.role] = t.fontSize; });

    const weights = new Set<number>();
    typo.forEach((t: any) => weights.add(t.fontWeight));
    const weightObj: Record<string, number> = {};
    // Map each weight to its correct CSS name instead of guessing by sort order
    const weightNameMap: Record<number, string> = {
      100: 'thin', 200: 'extralight', 300: 'light', 400: 'regular',
      500: 'medium', 600: 'semibold', 700: 'bold', 800: 'extrabold', 900: 'black'
    };
    Array.from(weights).sort((a, b) => a - b).forEach(w => {
      const name = weightNameMap[w] || `w${w}`;
      weightObj[name] = w;
    });

    const lhSet = new Set<number>();
    typo.forEach((t: any) => lhSet.add(t.lineHeight));
    const lhObj: Record<string, number> = {};
    const lhNames = ['tight', 'snug', 'normal', 'relaxed'];
    Array.from(lhSet).sort().forEach((lh, i) => { lhObj[lhNames[i] || `lh${i}`] = lh; });

    const layout = data.layout || {};
    const borders = data.borders || {};

    const shadowObj: Record<string, string> = {};
    (data.shadows || []).forEach((s: any) => { if (!shadowObj[s.category]) shadowObj[s.category] = s.raw; });

    const transObj: Record<string, string> = {};
    const tNames = ['fast', 'default', 'medium', 'slow'];
    (data.animations || []).slice(0, 4).forEach((t: any, i: number) => {
      transObj[tNames[i]] = `${t.duration} ${t.easing}`;
    });
    if (!Object.keys(transObj).length) transObj['default'] = '150ms ease';

    const bpObj: Record<string, string> = {};
    const bpNames = ['sm', 'md', 'lg', 'xl', '2xl'];
    (data.breakpoints?.breakpoints || []).forEach((bp: string, i: number) => {
      bpObj[bpNames[i] || `bp${i}`] = bp;
    });

    const tokens = {
      colors: {
        background: bg, surface, border,
        text: { primary: textP, secondary: textS, muted: textM },
        accent: { base: accent }
      },
      typography: {
        fontFamily: { heading: headingFont, body: bodyFont },
        fontSize: fontSizes,
        fontWeight: weightObj,
        lineHeight: lhObj
      },
      spacing: {
        container: layout.containerMaxWidth || '1280px',
        sectionY: layout.sectionPaddingY || '5rem',
        sectionX: layout.sectionPaddingX || '1.5rem',
        cardPadding: layout.cardPadding || '1.5rem',
        gridGap: layout.gridGap || '1.5rem'
      },
      borders: {
        radius: (borders.radius || []).slice(0, 5),
        defaultRadius: borders.defaultRadius || '8px',
        pillRadius: borders.pillRadius
      },
      shadows: shadowObj,
      transitions: transObj,
      breakpoints: bpObj,
      googleFontsUrl: data.fontStack?.googleFontsUrl
    };

    return `// Generated by DesignLift from ${url}\n// Extracted: ${date}\n\nexport const designTokens = ${JSON.stringify(tokens, null, 2)};\n`;
  },

  // ─── TAILWIND CONFIG ────────────────────────────────────────────────

  toTailwindConfig(data: any): string {
    const bg = this._getColor(data, 'background') || '#ffffff';
    const surface = this._getColor(data, 'surface') || '#f5f5f5';
    const border = this._getColor(data, 'border') || '#e5e5e5';
    const accent = this._getColor(data, 'accent') || '#3b82f6';

    const typo = data.typography || [];
    const headingFont = typo.find((t: any) => ['hero', 'h1'].includes(t.role))?.fontFamily;
    const bodyFont = typo.find((t: any) => t.role === 'body')?.fontFamily;

    const extend: any = {
      colors: {
        background: bg, surface, border,
        accent: { DEFAULT: accent }
      }
    };

    if (headingFont || bodyFont) {
      extend.fontFamily = {};
      if (headingFont) extend.fontFamily.heading = headingFont.split(',').map((f: string) => f.trim());
      if (bodyFont) extend.fontFamily.body = bodyFont.split(',').map((f: string) => f.trim());
    }

    if (data.layout?.containerMaxWidth) {
      extend.maxWidth = { container: data.layout.containerMaxWidth };
    }

    const shadows: Record<string, string> = {};
    (data.shadows || []).forEach((s: any) => { if (!shadows[s.category]) shadows[s.category] = s.raw; });
    if (Object.keys(shadows).length) extend.boxShadow = shadows;

    return `// Generated by DesignLift — extend your existing Tailwind config with these tokens

import type { Config } from 'tailwindcss'

const designLiftExtend: Partial<Config['theme']> = {
  extend: ${JSON.stringify(extend, null, 4)}
}

export default designLiftExtend
`;
  },

  // ─── CSS VARIABLES ──────────────────────────────────────────────────

  toCssVars(data: any): string {
    const url = data.sourceUrl || 'unknown';
    const lines = [`/* Generated by DesignLift from ${url} */`, '', ':root {'];

    const add = (name: string, val: string) => { if (val) lines.push(`  --dl-${name}: ${val};`); };

    add('bg', this._getColor(data, 'background'));
    add('surface', this._getColor(data, 'surface'));
    add('border', this._getColor(data, 'border'));
    add('text', this._getColor(data, 'text-primary'));
    add('text-secondary', this._getColor(data, 'text-secondary'));
    add('text-muted', this._getColor(data, 'text-muted'));
    add('accent', this._getColor(data, 'accent'));

    const borders = data.borders || {};
    const rNames = ['sm', 'md', 'lg', 'xl'];
    (borders.radius || []).slice(0, 4).forEach((r: string, i: number) => {
      add(`radius-${rNames[i]}`, r);
    });

    (data.shadows || []).slice(0, 4).forEach((s: any) => {
      add(`shadow-${s.category}`, s.raw);
    });

    if (data.layout?.containerMaxWidth) add('container', data.layout.containerMaxWidth);

    const typo = data.typography || [];
    const hf = typo.find((t: any) => ['hero', 'h1'].includes(t.role))?.fontFamily;
    const bf = typo.find((t: any) => t.role === 'body')?.fontFamily;
    if (hf) add('font-heading', hf);
    if (bf) add('font-body', bf);

    const anim = data.animations?.[0];
    if (anim) add('transition', `${anim.duration} ${anim.easing}`);

    lines.push('}', '');
    return lines.join('\n');
  },

  // ─── JSON TOKENS ────────────────────────────────────────────────────

  toJson(data: any): string {
    return JSON.stringify({
      sourceUrl: data.sourceUrl,
      timestamp: data.timestamp,
      colors: data.colors,
      typography: data.typography,
      fontStack: data.fontStack,
      spacing: data.spacing,
      layout: data.layout,
      borders: data.borders,
      shadows: data.shadows,
      animations: data.animations,
      breakpoints: data.breakpoints
    }, null, 2);
  },

  // ─── JSX COMPONENTS ────────────────────────────────────────────────

  structureToJsx(structure: any): string {
    if (!structure?.html) return '// No structure data available';

    let jsx = structure.html;
    // class → className
    jsx = jsx.replace(/\bclass="/g, 'className="');

    return `// Generated by DesignLift from ${structure.sourceUrl}
// Sections: ${(structure.sections || []).map((s: any) => s.type).join(', ')}

export default function ClonedPage() {
  return (
    <>
${jsx.split('\n').map((line: string) => '      ' + line).join('\n')}
    </>
  )
}
`;
  }
};
